### Create a new Product
Post http://localhost:3000/products/create-prooduct
Content-Type: application/json

{
    "name": "abc",
    "description": "Lool1122new4",
    "price":"123"
}

### Get All Products
Get http://localhost:3000/products/get-all-products

### Get Product By Id
Get http://localhost:3000/products/15278

### Update Product
Put http://localhost:3000/products/15280
Content-Type: application/json

{
    "name": "abcd",
    "description": "Lool1122new4",
    "price":"123"
}   
